# run the command below and set `local_backend: true` for local development
# npx netlify-cms-proxy-server
local_backend: true
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
# publish_mode: editorial_workflow # didn't work when testing locally...
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
publish_mode: editorial_workflow
collections:
  - name: "homepage"
    label: "Homepage"
    extension: "md"
    folder: "src/pages/cms/homepage"
    create: false # Allow users to create new documents in this collection
    slug: "{{title}}"
    fields:
      - { name: "title", label: "Title (<h1>)", widget: "string" }
      - { name: "text", label: "text", widget: "markdown" }
  - name: "blog"
    label: "Blogs"
    folder: "src/pages/blogs"
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    fields:
      - {name: "slug", label: "slug", widget: "string"}
      - {name: "title", label: "title", widget: "string" }
      - {name: "main", label : "main", widget : "markdown" }
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - name: author
        label: Author
        widget: relation
        collection: authors
        searchFields: [name]
        valueField: "name"
        displayFields: [name]
      - label: "Categories"
        name: "Categories"
        widget: "select"
        multiple: true
        options:
          - { label: "Recruitment", value: "Recruitment" }
          - { label: "Test", value: "Test" }
          - { label: "Candidates", value: "Candidates" }
  - name: authors
    label: Authors
    folder: "src/pages/_authors"
    create: true
    slug: "{{name}}"
    fields:
      - {name: name, label: Name , widget: "string"}