# run the command below and set `local_backend: true` for local development
# npx netlify-cms-proxy-server
local_backend: true
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# publish_mode: editorial_workflow # didn't work when testing locally...
display_url: https://routify-netlifycms.netlify.app
logo_url: https://routify-netlifycms.netlify.app/images/hero.jpg
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "homepage"
    label: "Homepage"
    extension: "md"
    folder: "src/pages/cms/homepage"
    create: false # Allow users to create new documents in this collection
    slug: "{{title}}"
    fields:
      - { name: "title", label: "Title (<h1>)", widget: "string" }
      - { name: "text", label: "text", widget: "markdown" }
  - name: "blog"
    label: "Blogs"
    folder: "src/pages/blogs"
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    fields:
      - {name: "slug", label: "slug", widget: "string"}
      - { name: "title", label: "title", widget: "string" }
      - {label: "Featured Image", name: "thumbnail", widget: "image"}